// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport_catalogue.proto

#include "transport_catalogue.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace t_c_srlz {
PROTOBUF_CONSTEXPR TransportCatalogue::TransportCatalogue(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.list_stop_)*/{}
  , /*decltype(_impl_.list_bus_)*/{}
  , /*decltype(_impl_.list_stop_lenght_)*/{}
  , /*decltype(_impl_.render_settings_)*/nullptr
  , /*decltype(_impl_.t_r__)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TransportCatalogueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TransportCatalogueDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TransportCatalogueDefaultTypeInternal() {}
  union {
    TransportCatalogue _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TransportCatalogueDefaultTypeInternal _TransportCatalogue_default_instance_;
}  // namespace t_c_srlz
static ::_pb::Metadata file_level_metadata_transport_5fcatalogue_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_transport_5fcatalogue_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_transport_5fcatalogue_2eproto = nullptr;

const uint32_t TableStruct_transport_5fcatalogue_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::t_c_srlz::TransportCatalogue, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::t_c_srlz::TransportCatalogue, _impl_.list_stop_),
  PROTOBUF_FIELD_OFFSET(::t_c_srlz::TransportCatalogue, _impl_.list_bus_),
  PROTOBUF_FIELD_OFFSET(::t_c_srlz::TransportCatalogue, _impl_.list_stop_lenght_),
  PROTOBUF_FIELD_OFFSET(::t_c_srlz::TransportCatalogue, _impl_.render_settings_),
  PROTOBUF_FIELD_OFFSET(::t_c_srlz::TransportCatalogue, _impl_.t_r__),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::t_c_srlz::TransportCatalogue)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::t_c_srlz::_TransportCatalogue_default_instance_._instance,
};

const char descriptor_table_protodef_transport_5fcatalogue_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\031transport_catalogue.proto\022\010t_c_srlz\032\036d"
  "ata_transport_catalogue.proto\032\022map_rende"
  "rer.proto\032\026transport_router.proto\"\353\001\n\022Tr"
  "ansportCatalogue\022#\n\tlist_stop\030\001 \003(\0132\020.d_"
  "t_c_srlz.Stop\022!\n\010list_bus\030\002 \003(\0132\017.d_t_c_"
  "srlz.Bus\0221\n\020list_stop_lenght\030\003 \003(\0132\027.d_t"
  "_c_srlz.StopsLenght\0221\n\017render_settings\030\004"
  " \001(\0132\030.r_s_srlz.RenderSettings\022\'\n\004t_r_\030\005"
  " \001(\0132\031.t_r_srlz.TransportRouterb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_transport_5fcatalogue_2eproto_deps[3] = {
  &::descriptor_table_data_5ftransport_5fcatalogue_2eproto,
  &::descriptor_table_map_5frenderer_2eproto,
  &::descriptor_table_transport_5frouter_2eproto,
};
static ::_pbi::once_flag descriptor_table_transport_5fcatalogue_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_transport_5fcatalogue_2eproto = {
    false, false, 359, descriptor_table_protodef_transport_5fcatalogue_2eproto,
    "transport_catalogue.proto",
    &descriptor_table_transport_5fcatalogue_2eproto_once, descriptor_table_transport_5fcatalogue_2eproto_deps, 3, 1,
    schemas, file_default_instances, TableStruct_transport_5fcatalogue_2eproto::offsets,
    file_level_metadata_transport_5fcatalogue_2eproto, file_level_enum_descriptors_transport_5fcatalogue_2eproto,
    file_level_service_descriptors_transport_5fcatalogue_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_transport_5fcatalogue_2eproto_getter() {
  return &descriptor_table_transport_5fcatalogue_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_transport_5fcatalogue_2eproto(&descriptor_table_transport_5fcatalogue_2eproto);
namespace t_c_srlz {

// ===================================================================

class TransportCatalogue::_Internal {
 public:
  static const ::r_s_srlz::RenderSettings& render_settings(const TransportCatalogue* msg);
  static const ::t_r_srlz::TransportRouter& t_r_(const TransportCatalogue* msg);
};

const ::r_s_srlz::RenderSettings&
TransportCatalogue::_Internal::render_settings(const TransportCatalogue* msg) {
  return *msg->_impl_.render_settings_;
}
const ::t_r_srlz::TransportRouter&
TransportCatalogue::_Internal::t_r_(const TransportCatalogue* msg) {
  return *msg->_impl_.t_r__;
}
void TransportCatalogue::clear_list_stop() {
  _impl_.list_stop_.Clear();
}
void TransportCatalogue::clear_list_bus() {
  _impl_.list_bus_.Clear();
}
void TransportCatalogue::clear_list_stop_lenght() {
  _impl_.list_stop_lenght_.Clear();
}
void TransportCatalogue::clear_render_settings() {
  if (GetArenaForAllocation() == nullptr && _impl_.render_settings_ != nullptr) {
    delete _impl_.render_settings_;
  }
  _impl_.render_settings_ = nullptr;
}
void TransportCatalogue::clear_t_r_() {
  if (GetArenaForAllocation() == nullptr && _impl_.t_r__ != nullptr) {
    delete _impl_.t_r__;
  }
  _impl_.t_r__ = nullptr;
}
TransportCatalogue::TransportCatalogue(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:t_c_srlz.TransportCatalogue)
}
TransportCatalogue::TransportCatalogue(const TransportCatalogue& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TransportCatalogue* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.list_stop_){from._impl_.list_stop_}
    , decltype(_impl_.list_bus_){from._impl_.list_bus_}
    , decltype(_impl_.list_stop_lenght_){from._impl_.list_stop_lenght_}
    , decltype(_impl_.render_settings_){nullptr}
    , decltype(_impl_.t_r__){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_render_settings()) {
    _this->_impl_.render_settings_ = new ::r_s_srlz::RenderSettings(*from._impl_.render_settings_);
  }
  if (from._internal_has_t_r_()) {
    _this->_impl_.t_r__ = new ::t_r_srlz::TransportRouter(*from._impl_.t_r__);
  }
  // @@protoc_insertion_point(copy_constructor:t_c_srlz.TransportCatalogue)
}

inline void TransportCatalogue::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.list_stop_){arena}
    , decltype(_impl_.list_bus_){arena}
    , decltype(_impl_.list_stop_lenght_){arena}
    , decltype(_impl_.render_settings_){nullptr}
    , decltype(_impl_.t_r__){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TransportCatalogue::~TransportCatalogue() {
  // @@protoc_insertion_point(destructor:t_c_srlz.TransportCatalogue)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TransportCatalogue::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.list_stop_.~RepeatedPtrField();
  _impl_.list_bus_.~RepeatedPtrField();
  _impl_.list_stop_lenght_.~RepeatedPtrField();
  if (this != internal_default_instance()) delete _impl_.render_settings_;
  if (this != internal_default_instance()) delete _impl_.t_r__;
}

void TransportCatalogue::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TransportCatalogue::Clear() {
// @@protoc_insertion_point(message_clear_start:t_c_srlz.TransportCatalogue)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.list_stop_.Clear();
  _impl_.list_bus_.Clear();
  _impl_.list_stop_lenght_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.render_settings_ != nullptr) {
    delete _impl_.render_settings_;
  }
  _impl_.render_settings_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.t_r__ != nullptr) {
    delete _impl_.t_r__;
  }
  _impl_.t_r__ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TransportCatalogue::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .d_t_c_srlz.Stop list_stop = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_list_stop(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .d_t_c_srlz.Bus list_bus = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_list_bus(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .d_t_c_srlz.StopsLenght list_stop_lenght = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_list_stop_lenght(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      // .r_s_srlz.RenderSettings render_settings = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_render_settings(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .t_r_srlz.TransportRouter t_r_ = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_t_r_(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TransportCatalogue::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:t_c_srlz.TransportCatalogue)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .d_t_c_srlz.Stop list_stop = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_list_stop_size()); i < n; i++) {
    const auto& repfield = this->_internal_list_stop(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .d_t_c_srlz.Bus list_bus = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_list_bus_size()); i < n; i++) {
    const auto& repfield = this->_internal_list_bus(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .d_t_c_srlz.StopsLenght list_stop_lenght = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_list_stop_lenght_size()); i < n; i++) {
    const auto& repfield = this->_internal_list_stop_lenght(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  // .r_s_srlz.RenderSettings render_settings = 4;
  if (this->_internal_has_render_settings()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::render_settings(this),
        _Internal::render_settings(this).GetCachedSize(), target, stream);
  }

  // .t_r_srlz.TransportRouter t_r_ = 5;
  if (this->_internal_has_t_r_()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::t_r_(this),
        _Internal::t_r_(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:t_c_srlz.TransportCatalogue)
  return target;
}

size_t TransportCatalogue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:t_c_srlz.TransportCatalogue)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .d_t_c_srlz.Stop list_stop = 1;
  total_size += 1UL * this->_internal_list_stop_size();
  for (const auto& msg : this->_impl_.list_stop_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .d_t_c_srlz.Bus list_bus = 2;
  total_size += 1UL * this->_internal_list_bus_size();
  for (const auto& msg : this->_impl_.list_bus_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .d_t_c_srlz.StopsLenght list_stop_lenght = 3;
  total_size += 1UL * this->_internal_list_stop_lenght_size();
  for (const auto& msg : this->_impl_.list_stop_lenght_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .r_s_srlz.RenderSettings render_settings = 4;
  if (this->_internal_has_render_settings()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.render_settings_);
  }

  // .t_r_srlz.TransportRouter t_r_ = 5;
  if (this->_internal_has_t_r_()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.t_r__);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TransportCatalogue::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TransportCatalogue::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TransportCatalogue::GetClassData() const { return &_class_data_; }


void TransportCatalogue::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TransportCatalogue*>(&to_msg);
  auto& from = static_cast<const TransportCatalogue&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:t_c_srlz.TransportCatalogue)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.list_stop_.MergeFrom(from._impl_.list_stop_);
  _this->_impl_.list_bus_.MergeFrom(from._impl_.list_bus_);
  _this->_impl_.list_stop_lenght_.MergeFrom(from._impl_.list_stop_lenght_);
  if (from._internal_has_render_settings()) {
    _this->_internal_mutable_render_settings()->::r_s_srlz::RenderSettings::MergeFrom(
        from._internal_render_settings());
  }
  if (from._internal_has_t_r_()) {
    _this->_internal_mutable_t_r_()->::t_r_srlz::TransportRouter::MergeFrom(
        from._internal_t_r_());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TransportCatalogue::CopyFrom(const TransportCatalogue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:t_c_srlz.TransportCatalogue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TransportCatalogue::IsInitialized() const {
  return true;
}

void TransportCatalogue::InternalSwap(TransportCatalogue* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.list_stop_.InternalSwap(&other->_impl_.list_stop_);
  _impl_.list_bus_.InternalSwap(&other->_impl_.list_bus_);
  _impl_.list_stop_lenght_.InternalSwap(&other->_impl_.list_stop_lenght_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TransportCatalogue, _impl_.t_r__)
      + sizeof(TransportCatalogue::_impl_.t_r__)
      - PROTOBUF_FIELD_OFFSET(TransportCatalogue, _impl_.render_settings_)>(
          reinterpret_cast<char*>(&_impl_.render_settings_),
          reinterpret_cast<char*>(&other->_impl_.render_settings_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TransportCatalogue::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_transport_5fcatalogue_2eproto_getter, &descriptor_table_transport_5fcatalogue_2eproto_once,
      file_level_metadata_transport_5fcatalogue_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace t_c_srlz
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::t_c_srlz::TransportCatalogue*
Arena::CreateMaybeMessage< ::t_c_srlz::TransportCatalogue >(Arena* arena) {
  return Arena::CreateMessageInternal< ::t_c_srlz::TransportCatalogue >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
